name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - v3
  pull_request_target:
    branches:
      - main
      - master
      - v3

jobs:
  pipeline:
    name: CI Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci --force # TODO: Remove force later
      - name: Run Svelte Check
        run: npm run check
      - name: Generate AUTH_SECRET
        run: echo "AUTH_SECRET=$(openssl rand -base64 33)" >> $GITHUB_ENV
      - name: Download & extract database binary
        run: |
          wget https://binaries.cockroachdb.com/cockroach-v24.1.1.linux-amd64.tgz
          tar -xvzf cockroach-v24.1.1.linux-amd64.tgz
      - name: Start database server
        run: ./cockroach-v24.1.1.linux-amd64/cockroach start-single-node --insecure --background
      - name: Initialize database schema
        run: npx prisma db push
        env:
          DATABASE_URL: 'postgresql://root@localhost:26257/defaultdb?sslmode=disable'
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          DATABASE_URL: 'postgresql://root@localhost:26257/defaultdb?sslmode=disable'
          AUTH_SECRET: ${{ env.AUTH_SECRET }}
        run: npx playwright test
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
